apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml

patches:
  - target:
      kind: BackendConfig
      name: developer-portal
    patch: |-
      - op: replace
        path: "/spec/healthCheck/requestPath"
        value: "/zilliqa1/"
  - target:
      kind: Deployment
      name: developer-portal
    patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/readinessProbe/httpGet/path"
        value: "/zilliqa1/"
      - op: replace
        path: "/spec/template/spec/containers/0/image"
        value: developer-portal-nozq2
  - target:
      kind: Ingress
      name: developer-portal
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: dev.zilliqa.com
      - op: remove
        path: "/spec/rules/1"
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: dev-zilliqa-com
          networking.gke.io/managed-certificates: developer-portal
          networking.gke.io/v1beta1.FrontendConfig: developer-portal

namespace: developer-portal-prd
