apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: developer-portal
  namespace: developer-portal
  labels:
    app.kubernetes.io/name: "developer-portal"
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        requestPath: /health
        port: 80
  targetRef:
    group: ""
    kind: Service
    name: developer-portal
