name: "Linting"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    name: "Linting"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: "Installing dependencies"
        run: |
          pnpm i

      - name: Trunk cache
        id: cache-trunk
        uses: actions/cache@v4.2.2
        with:
          path: ~/.cache/trunk/
          key: ${{ runner.os }}-trunk

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1.1.19
